- CODEOWNERS
Samia wants better visibility on how who owns what in DBT, to this end we should add a [CODEOWNERS](https://www.arnica.io/blog/what-every-developer-should-know-about-github-codeowners) file to the report-a-breach repo which stores the name of the team that owns the project.
> DST-284 - Adding a CODEOWNERS file

- report_a_breach/core/views.py
- report_a_breach/templates/form_steps/summary.html
This was removed accidentally in another PR.
The sanctions ticked on the which_sanctions_regime page will be displayed again to the end user on the summary page.
> Sanctions selected should be displayed to the end user

- report_a_breach/base_classes/views.py
The assignment to redirect_to in the render method was a boolean which meant the actual redirect page name wasn't passed into the render_goto_step method. This is corrected by moving the if form.is_valid into a separate condition check.
> DST-301: Fix redirect logic from the summary page

- report_a_breach/core/form_step_conditions.py
- report_a_breach/core/forms.py
JIRA ticket: https://uktrade.atlassian.net/browse/DST-323
This ticket fixes a bug in the user journey where previously when the user selected "I do not know" on the "are you reporting a company registered on companies house" form, they would continue onto the "do you know the registered company number" form.
Now, the user will continue to "Where is the address of the person who made the suspected breach" form.
> DST-323: Fix user journey when companies house number is unknown

- report_a_breach/base_classes/forms.py
- report_a_breach/core/forms.py
Selecting "They have not been supplied yet" on the "supplied to" page results in a 500 error. This is because the address dict that the "made_available_from" form expects was actually passed in as a string from the kwargs. This PR fixes the error and allows the user to enter the start of the "made available from" journey. More work on the made_available journey to be completed as part of ticket DST-328.
> Fix 500 error when selecting "have not been supplied yet"

- report_a_breach/core/form_step_conditions.py
- report_a_breach/core/forms.py
- report_a_breach/core/urls.py
- report_a_breach/core/views.py
- report_a_breach/custom_upload_handler.py
This journey starts when the user selects "They have not been supplied yet" on the supplied_to page. 
The next form "made_available_from" should always redirect to the "made_available_to" once the appropriate addresses are captured, if applicable.
The new logic from the made_available_from page is:
- same address -> redirect to made_available_to
- different uk address -> about the supplier address capture -> made_available_to
- outside address -> about the supplier address capture -> made_available_to
- I don't know -> redirect to made_available_to
The end-user address captures should follow from the made_available_to page, however that is not currently working and will be handled in a separate ticket (DST-346).
> DST-328: Create the made_available journey

- report_a_breach/base_classes/views.py
- report_a_breach/core/forms.py
- report_a_breach/core/views.py
- report_a_breach/templates/form_steps/end_user_added.html
- report_a_breach/templates/form_steps/summary.html
- report_a_breach/utils/companies_house.py
Bugfixes for [DST-332](https://uktrade.atlassian.net/browse/DST-332)
Screenshots for information: 
[DST-332]: https://uktrade.atlassian.net/browse/DST-332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Dst 332/bugfix cya page

- report_a_breach/core/urls.py
- report_a_breach/core/views.py
- report_a_breach/templates/form_steps/summary.html
Bugfixes as part of [DST-332](https://uktrade.atlassian.net/browse/DST-332) Check your answers page
[DST-332]: https://uktrade.atlassian.net/browse/DST-332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Dst 332/end user id change page

- django_app/feedback/forms.py
- django_app/report_a_suspected_breach/forms.py
- django_app/report_a_suspected_breach/static/report_a_suspected_breach/stylesheets/report_a_suspected_breach.css
- django_app/report_a_suspected_breach/templates/report_a_suspected_breach/form_steps/request_verify_code.html
the contact details in the text expander is now on a single line as per Peter's comment. https://uktrade.atlassian.net/browse/DST-359.
> DST-359: update email request code review comments

- django_app/report_a_suspected_breach/templates/report_a_suspected_breach/form_steps/summary.html
- django_app/report_a_suspected_breach/templates/report_a_suspected_breach/partials/summary_report.html
Updating to display "The UK" in the summary pages for location of supplier/end user if country is United Kingdom
> show the uk as location of enduser or supplier in summary

- Pipfile.lock
- django_app/report_a_suspected_breach/forms.py
- django_app/report_a_suspected_breach/views.py
The end user form did not show errors if the user selected continue without choosing an option. This PR fixes that by changing the form field to a ChoiceField with a radio select widget.
> DST-457: Fix end user form errors

- django_app/report_a_suspected_breach/static/report_a_suspected_breach/stylesheets/report_a_suspected_breach.css
- django_app/report_a_suspected_breach/templates/report_a_suspected_breach/partials/summary_report.html
FYI, I sent the images of the report to Peter and he's happy with the spacing/width of text.
> DST-394/confirmation page download report fixes

- Pipfile
- Pipfile.lock
- django_app/report_a_suspected_breach/views.py
Changed the back_button variable to contain the HTTP Referrer or None rather than the step_url. After local testing, this gives a more intuitive/improved user experience as the back button will send the user back to the page they previously visited if the referrer exists, else they will be sent to the task list page where they can then select the appropriate task to be redirected to the page they need.
> DST-351: Pass the referrer into the back_button variable

- django_app/report_a_suspected_breach/session.py
- tests/test_unit/test_report_a_suspected_breach/test_views/test_wizard_view.py
> DST-381: Change links for end user

- django_app/report_a_suspected_breach/forms.py
- django_app/report_a_suspected_breach/static/report_a_suspected_breach/javascript/which_sanctions_regime.js
- tests/test_unit/test_report_a_suspected_breach/test_forms.py
when click ‘I do not know’ you can still check ‘Other regime’. I think selecting Other regime should cancel out the I do not know, and vice versa
> Peter comments on DST-441 - Which sanctions regime page

- django_app/report_a_suspected_breach/views.py
- tests/test_unit/test_report_a_suspected_breach/test_views/test_zero_enduser_views.py
Removing I don't know option when user selects 'add an end user' from the zero end users page
> DST-438: Remove idk option if select add another end user

- django_app/config/settings/test.py
- django_app/core/custom_upload_handler.py
- django_app/report_a_suspected_breach/views.py
- tests/test_unit/test_report_a_suspected_breach/test_views/test_document_views.py
- Refactoring file upload handler to reduce length.
- Using the original name of the file to set the cache key as we don't want to display the session key to the end-user
> Fixing file upload to work on DBT Platform

- django_app/report_a_suspected_breach/form_step_conditions.py
The show condition was pointing at the incorrect dictionary key for the forms data. Updating the key has corrected the issue.
> DST-466: Fix user journey when they do not know companies house number

- django_app/core/templates/core/base.html
[Jira](https://uktrade.atlassian.net/browse/DST-762)
When the user is on a page other than task-list, and clicks to hide cookies, they were redirected to "/" which is the task-list. This PR fixes this behaviour by adding the redirect_back_to var into the form submission.
> DST-762: Fix hide_cookies redirect

- django_app/report_a_suspected_breach/static/report_a_suspected_breach/stylesheets/report_a_suspected_breach.css
- django_app/report_a_suspected_breach/templates/report_a_suspected_breach/form_steps/check_your_answers.html
- django_app/report_a_suspected_breach/views/views_supply_chain.py
- tests/test_unit/test_report_a_suspected_breach/test_views/data.py
- tests/test_unit/test_report_a_suspected_breach/test_views/test_views_end.py
- tests/test_unit/test_report_a_suspected_breach/test_views/test_views_supply_chain.py
If no end users: 
1 end user: 
2 end users:
Also in this PR but done after taking screenshots: 
Removed location of end user as per figma / content SoT
Updated link colour
Adding tests for views_end
> DST-632: remove end users from cya page

- django_app/core/templates/core/base_form_step.html
- tests/test_frontend/test_core/test_base_form_step_title_error_message.py
> DST-1034 - Adding 'Error: ' to title browser tab text when errors appear

- django_app/healthcheck/checks/__init__.py
- django_app/healthcheck/checks/db.py
- django_app/healthcheck/views.py
- tests/test_unit/test_healthcheck.py
Sentry recommends using threads or sync_to_async. Used threads via asyncio and updated the unit test to await the return. Deployed successfully to dev and tested the app.
> DST-1024: SynchronousOnly Sentry error
