uktrade/report-a-breach

- .env.example
- config/settings/base.py
- report_a_breach/templates/base.html
- report_a_breach/templatetags/get_gtm_id.py
- report_a_breach/templatetags/gtm_enabled.py
implement Google Analytics cookies to report-a-breach
> Adding google analytics cookies

- .env.example
- Pipfile
- Pipfile.lock
- README.md
- django_app/config/env.py
- django_app/config/settings/base.py
- django_app/core/urls.py
- django_app/view_a_suspected_breach/views.py
- docker-compose.yml
> DST-330 - Staff SSO

- django_app/config/settings/test.py
- django_app/healthcheck/checks/s3.py
- django_app/healthcheck/urls.py
- django_app/healthcheck/views.py
- django_app/utils/companies_house.py
- pyproject.toml
- tasks.py
- tests/conftest.py
- tests/helpers.py
- tests/test_unit/test_companies_house.py
- tests/test_unit/test_healthcheck.py
- tests/test_unit/test_report_a_suspected_breach/test_forms.py
Added some more tests and added pytest fixtures to help with testing the multiple django sites.
Also fixed healthcheck view
> Adding some more unit tests

- django_app/report_a_suspected_breach/views.py
https://sentry.ci.uktrade.digital/organizations/dit/issues/115668/?project=231&query=is%3Aunresolved
> Attribute error bug fix

- django_app/report_a_suspected_breach/tasklist.py
- django_app/report_a_suspected_breach/templates/report_a_suspected_breach/tasklist.html
- tests/test_unit/test_report_a_suspected_breach/test_tasklist.py
> DST-358: Tasklist changes for completed

- .env.example
- docker-compose.yml
This makes it possible to have multiple versions of localstack running simultaneously
> Changing localstack port

- django_app/view_a_suspected_breach/templates/view_a_suspected_breach/view_a_suspected_breach.html
- django_app/view_a_suspected_breach/views.py
- tests/test_unit/test_view_a_suspected_breach/test_views/test_view_a_suspected_breach_view.py
https://uktrade.atlassian.net/browse/DST-396
> DST-396: Fixes for view a breach view

- django_app/report_a_suspected_breach/templates/report_a_suspected_breach/form_steps/check_company_details.html
- django_app/report_a_suspected_breach/templates/report_a_suspected_breach/form_steps/summary.html
Addressing couple issues with link text in the DAC accessiblity report:
> DST-346: non descriptive links

- django_app/report_a_suspected_breach/forms.py
> DST-439 - [Design bug] Give a summary of the breach

- django_app/config/env.py
- django_app/core/templates/core/base.html
- django_app/core/templates/core/cookies_consent.html
- django_app/feedback/templates/feedback/collect_feedback.html
- django_app/feedback/templates/feedback/feedback_done.html
- django_app/report_a_suspected_breach/templates/report_a_suspected_breach/base_form_step.html
- django_app/report_a_suspected_breach/templates/report_a_suspected_breach/complete.html
- django_app/report_a_suspected_breach/templates/report_a_suspected_breach/form_steps/check_company_details.html
- django_app/report_a_suspected_breach/templates/report_a_suspected_breach/form_steps/declaration.html
- django_app/report_a_suspected_breach/templates/report_a_suspected_breach/form_steps/end_user_added.html
- django_app/report_a_suspected_breach/templates/report_a_suspected_breach/form_steps/request_verify_code.html
- django_app/report_a_suspected_breach/templates/report_a_suspected_breach/form_steps/summary.html
- django_app/report_a_suspected_breach/templates/report_a_suspected_breach/form_steps/upload_documents.html
- django_app/report_a_suspected_breach/templates/report_a_suspected_breach/tasklist.html
- django_app/view_a_suspected_breach/templates/view_a_suspected_breach/landing.html
- django_app/view_a_suspected_breach/templates/view_a_suspected_breach/unauthorised.html
- django_app/view_a_suspected_breach/templates/view_a_suspected_breach/view_a_suspected_breach.html
Accessibility audit page title issue
> DST-435: page titles

- django_app/report_a_suspected_breach/templates/report_a_suspected_breach/complete.html
> DST-453 - Adding users email in the confirmation page

- Pipfile
- Pipfile.lock
- django_app/config/settings/base.py
- django_app/config/settings/test.py
- django_app/core/utils.py
- django_app/core/views.py
- django_app/report_a_suspected_breach/forms.py
- django_app/report_a_suspected_breach/templates/report_a_suspected_breach/form_steps/request_verify_code.html
- django_app/report_a_suspected_breach/views.py
- tests/test_unit/test_report_a_suspected_breach/test_views/test_email_verify_view.py
- tests/test_unit/test_report_a_suspected_breach/test_views/test_request_verify_code_view.py
> DST-444 - Medium - Multi-Factor Authentication Brute-Forcing

- django_app/report_a_suspected_breach/templates/report_a_suspected_breach/form_steps/summary.html
- django_app/report_a_suspected_breach/templates/report_a_suspected_breach/partials/summary_report.html
- django_app/report_a_suspected_breach/views.py
- django_app/utils/companies_house.py
- tests/test_unit/test_companies_house.py
1. Fix change link journey for changing end user location
2. Fix location of supplier/end-users
> Update CYA page with correct locations

- django_app/report_a_suspected_breach/forms.py
- django_app/report_a_suspected_breach/static/report_a_suspected_breach/javascript/which_sanctions_regime.js
- django_app/report_a_suspected_breach/templates/report_a_suspected_breach/form_steps/upload_documents.html
- tests/test_unit/test_report_a_suspected_breach/test_forms.py
> DST-441 - Error paths for 'Which sanctions regime do you suspect the business or person has breached?'

- django_app/utils/companies_house.py
Updating list of countries that are considered "In the UK" these are returned by companies house as the country.
> Update list of countries that are UK

- django_app/report_a_suspected_breach/forms.py
- django_app/report_a_suspected_breach/urls.py
- django_app/report_a_suspected_breach/views.py
- django_app/utils/companies_house.py
- tests/test_unit/test_report_a_suspected_breach/test_forms.py
- tests/test_unit/test_report_a_suspected_breach/test_views/test_enduser_views.py
- tests/test_unit/test_report_a_suspected_breach/test_views/test_zero_enduser_views.py
> DST-438: no end user page

- django_app/core/templates/core/base.html
- django_app/feedback/templates/feedback/collect_feedback.html
feedback page opens in new tab and back link removed as it no longer works as a result
> DST-389 - re-implementation of feedback question

- django_app/config/env.py
- django_app/config/settings/base.py
- django_app/report_a_suspected_breach/views.py
- tests/test_unit/test_report_a_suspected_breach/test_views/test_wizard_view.py
> DST-462: Send the confirmation email to the reporter

- django_app/core/templates/core/accessibility_statement.html
[Jira link](https://uktrade.atlassian.net/browse/DST-756)
> DST-756: H1/H2s accessibility statement updates

- django_app/report_a_suspected_breach/templates/report_a_suspected_breach/partials/summary_report.html
- django_app/report_a_suspected_breach/views/views_f.py
- django_app/view_a_suspected_breach/templates/view_a_suspected_breach/summary_reports.html
- django_app/view_a_suspected_breach/urls.py
- django_app/view_a_suspected_breach/views.py
- tests/factories.py
- tests/test_unit/test_view_a_suspected_breach/test_views/test_view_a_suspected_breach_view.py
- tests/test_unit/test_view_a_suspected_breach/test_views/test_view_authorisation.py
> DST-743 - RaB + Licensing - viewer portal case reference ID in URL not showing correctly

- django_app/report_a_suspected_breach/forms/base_forms.py
- django_app/report_a_suspected_breach/templates/report_a_suspected_breach/form_steps/check_your_answers.html
- tests/test_unit/test_report_a_suspected_breach/test_forms/test_forms_supply_chain.py
> DST-745: URLField for website address validation

- django_app/report_a_suspected_breach/templates/report_a_suspected_breach/partials/summary_report.html
- django_app/report_a_suspected_breach/views/views_end.py
- django_app/utils/breach_report.py
- django_app/view_a_suspected_breach/templates/view_a_suspected_breach/summary_reports.html
[JIRA](https://uktrade.atlassian.net/browse/DST-675)
> DST-675: Add None uploaded to summary reports in viewer

- django_app/feedback/models.py
- django_app/view_a_suspected_breach/templates/view_a_suspected_breach/view_feedback.html
- django_app/view_a_suspected_breach/urls.py
- django_app/view_a_suspected_breach/views.py
- tests/conftest.py
- tests/factories.py
- tests/test_unit/test_view_a_suspected_breach/test_views/test_view_feedback_view.py
A feedback view so we can send H-CSAT data to the M&E team easily.
> DST-765: feedback view

- django_app/config/settings/base.py
- django_app/core/base_views.py
- django_app/core/context_processors.py
- django_app/core/static/core/javascript/session_dialog.js
- django_app/core/static/core/stylesheets/common.css
- django_app/core/templates/core/base.html
- django_app/core/templates/core/base_form_step.html
- django_app/core/templates/core/session_expired.html
- django_app/core/urls.py
- django_app/core/utils.py
- django_app/core/views.py
- django_app/report_a_suspected_breach/views/views_start.py
- tests/conftest.py
- tests/test_frontend/conftest.py
- tests/test_frontend/test_session_expiry/test_session_expiry.py
- tests/test_unit/test_core/test_utils.py
- tests/test_unit/test_core/test_views/test_session_expiry.py
- tests/test_unit/test_core/text_context_processors.py
- tests/test_unit/test_utils.py
> DST-804 - RaB - Session timeout designs

- django_app/core/templates/core/base.html
- django_app/core/templates/core/session_expired.html
- django_app/view_a_suspected_breach/templates/view_a_suspected_breach/view_a_suspected_breach.html
Fixing JS not loading.
Also fixing session expiry on Viewer.
Adding page title to session expiry
> General bug fixes

- django_app/report_a_suspected_breach/templates/report_a_suspected_breach/tasklist.html
Tasklist hover state only on tasks that can start
https://github.com/user-attachments/assets/b71e3f99-efdb-4774-9f61-42f5d2bdbb8c
> DST-693: tasklist hover states

- django_app/report_a_suspected_breach/models.py
- django_app/utils/breach_report.py
- tests/test_unit/test_report_a_suspected_breach/test_models/test_person_or_company.py
Fixing issue with previously submitted reports that created Organisations with registered_office_address but not address lines
> Chris - Bugfix - 2024-12-18

- django_app/report_a_suspected_breach/templates/report_a_suspected_breach/form_steps/check_your_answers.html
- django_app/report_a_suspected_breach/templates/report_a_suspected_breach/form_steps/end_user_added.html
- django_app/report_a_suspected_breach/templates/report_a_suspected_breach/partials/summary_report.html
- tests/test_frontend/test_report_a_suspected_breach/test_summary_and_declaration/test_check_your_answers.py
> DST-886: Add business name to cya

- Pipfile
- Pipfile.lock
CVE-2024-53907
CVE-2024-53908
CVE-2024-53861
> Security Fixes

- django_app/core/templates/core/base.html
- django_app/core/templates/core/help_and_support.html
- django_app/core/urls.py
- django_app/core/views.py
> DST-968: Help and support page

- django_app/report_a_suspected_breach/views/views_end.py
- tests/test_unit/test_report_a_suspected_breach/test_views/test_views_end.py
Redirect the user to the start page if there is a session issue on the complete page
> DST-988 - RAB - Breach.DoesNotExist error on Prod

- Pipfile
- Pipfile.lock
https://github.com/uktrade/report-a-breach/security/dependabot/28
> bump django version

- django_app/core/templates/core/help_and_support.html
> DST-1028: line break in help and support page
